

// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    url: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 3.5,
  },
  {
    id: 2,
    title: "Atomic Habits",
    url: "https://covers.openlibrary.org/b/id/10958382-L.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    url: "https://covers.openlibrary.org/b/id/10425061-L.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Deep Work",
    url: "https://covers.openlibrary.org/b/id/10088428-L.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The 10X Rule",
    url: "https://covers.openlibrary.org/b/id/9978588-L.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    url: "https://covers.openlibrary.org/b/id/7737110-L.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    url: "https://covers.openlibrary.org/b/id/2380224-L.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 2.5,
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    url: "https://covers.openlibrary.org/b/id/1954899-L.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "48 Laws of Power Summary",
    url: "https://covers.openlibrary.org/b/id/8906626-L.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 3.5,
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    url: "https://covers.openlibrary.org/b/id/8114155-L.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    url: "https://covers.openlibrary.org/b/id/7895280-L.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "Mastery",
    url: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
  {
    id: 13,
    title: "Twelve and a Half",
    url: "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/0626/9780062674685.jpg",
    originalPrice: 29.50,
    salePrice: null,
    rating: 5,
  },
  {
    id: 14,
    title: "Greatness Is Upon You",
    url: "https://rares.images.hpb.com/10377437/1/large.jpg",
    originalPrice: 49.50,
    salePrice: null,
    rating: 5,
  },
  {
    id: 15,
    title: "Crushing It!",
    url: "https://images-na.ssl-images-amazon.com/images/I/51SxLaKwSaL._SX329_BO1,204,203,200_.jpg",
    originalPrice: 40.0,
    salePrice: 39.99,
    rating: 4.5,
  },
  {
    id: 16,
    title: "The subtle Art of Not  Giving    A Fuck",
    url: "https://www.brit.co/media-library/image.jpg?id=26117338&width=704&quality=80",
    originalPrice: 40.0,
    salePrice: 39.99,
    rating: 4.5,
  },
];